image: artifactory.f5net.com/velocity-platform-docker-dev/datapath-builder:1.6.1

# This is the source for the prepare and release stages of the pipeline.
include:
  project: velocity/common/platform-semrel
  file: ci-include/v1/semrel.yml

stages:
  - prepare
  - quality
  - build
  - publish
  - release

before_script:
  - source /opt/rh/devtoolset-7/enable

prepare:version:
  stage: prepare
  extends: .release-prepare

quality:
  stage: quality
  tags:
    - velocity-platform-runner
  script:
    - make cppcheck

build:
  stage: build
  tags:
     - velocity-platform-runner
  script:
    - make
    - make rpm
  artifacts:
    paths:
      - obj
      - rpmbuild/RPMS/x86_64
    expire_in: 1 day

publish:
  stage: publish
  tags:
    - velocity-platform-runner
  script:
    - make publish
  only:
    refs:
      - master

release:changelog:
  stage: release
  extends: .release-changelog
  after_script:
    - make release
